#ifndef H_BRIDGE_CONFIG
#define H_BRIDGE_CONFIG

#define H_BRIDGE_PORT GPIO_PORTB
#define H_BRIDGE_PORT_CLOCK RCC_GPIOB
#define H_BRIDGE_PIN_IN1 PIN0
#define H_BRIDGE_PIN_IN2 PIN1
#define H_BRIDGE_PIN_EA PIN0
#define H_BRIDGE_PIN_EB

#endif /* H_BRIDGE_CONFIG */
