#include "LIBRARY/STD_TYPES.h"
#include "LIBRARY/BIT_MATH.h"
#include "GPIO/GPIO_interface.h"
#include "RCC/RCC_interface.h"
#include "TIMER/TIMER_interface.h"

#include "MOTORS/MOTORS_config.h"
#include "MOTORS/MOTORS_interface.h"

void MOTORS_init()
{
	// RCC
	RCC_PeripheralClockEnable(RCC_APB2, MOTORS_PORT_CLOCK); // enable motor port clock
	RCC_PeripheralClockEnable(RCC_APB1, RCC_TIM2);			// enable timer2 clock
	RCC_PeripheralClockEnable(RCC_APB2, RCC_GPIOA);			// enable gpioa clock

	// TIMER
	TIMER_Init(TIMER_NUM_2, TIMER_CHANNEL_1); // enable timer 2 channel 1

	// GPIO
	GPIO_SetPinMode(MOTORS_PORT, MOTORS_PIN_M1IN1, GPIO_OUTPUT_GP_PP_10MHZ); // motor driver gpio mode
	GPIO_SetPinMode(MOTORS_PORT, MOTORS_PIN_M1IN2, GPIO_OUTPUT_GP_PP_10MHZ);
	GPIO_SetPinMode(MOTORS_PORT, MOTORS_PIN_M2IN1, GPIO_OUTPUT_GP_PP_10MHZ);
	GPIO_SetPinMode(MOTORS_PORT, MOTORS_PIN_M2IN2, GPIO_OUTPUT_GP_PP_10MHZ);
	GPIO_SetPinMode(MOTORS_PORT, MOTORS_PIN_M3IN1, GPIO_OUTPUT_GP_PP_10MHZ);
	GPIO_SetPinMode(MOTORS_PORT, MOTORS_PIN_M3IN2, GPIO_OUTPUT_GP_PP_10MHZ);
	GPIO_SetPinMode(MOTORS_PORT, MOTORS_PIN_M4IN1, GPIO_OUTPUT_GP_PP_10MHZ);
	GPIO_SetPinMode(MOTORS_PORT, MOTORS_PIN_M4IN2, GPIO_OUTPUT_GP_PP_10MHZ);
	GPIO_SetPinMode(GPIO_PORTA, MOTORS_PIN_EN, GPIO_OUTPUT_ALT_PP_10MHZ);
}

void MOTORS_setDirection(u8 Direction)
{
	switch (Direction)
	{
	case STOP: // make all motors stop
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M1IN1, GPIO_LOW);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M1IN2, GPIO_LOW);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M2IN1, 1);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M2IN2, 1);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M3IN1, GPIO_LOW);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M3IN2, GPIO_LOW);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M4IN1, GPIO_LOW);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M4IN2, GPIO_LOW);
		break;
	case FORWARD: // make all motors rotate clockwise
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M1IN1, GPIO_HIGH);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M1IN2, GPIO_LOW);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M2IN1, GPIO_HIGH);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M2IN2, GPIO_LOW);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M3IN1, GPIO_HIGH);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M3IN2, GPIO_LOW);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M4IN1, GPIO_HIGH);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M4IN2, GPIO_LOW);
		break;
	case BACKWARD: // make all motors rotate anticlockwise
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M1IN1, GPIO_LOW);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M1IN2, GPIO_HIGH);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M2IN1, GPIO_LOW);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M2IN2, GPIO_HIGH);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M3IN1, GPIO_LOW);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M3IN2, GPIO_HIGH);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M4IN1, GPIO_LOW);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M4IN2, GPIO_HIGH);
		break;
	case RIGHT: // make the two motors on the left of the car rotate clockwise
				// and the two motors on the right of the car rotate anticlockwise
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M1IN1, GPIO_HIGH);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M1IN2, GPIO_LOW);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M2IN1, GPIO_HIGH);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M2IN2, GPIO_LOW);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M3IN1, GPIO_LOW);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M3IN2, GPIO_HIGH);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M4IN1, GPIO_LOW);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M4IN2, GPIO_HIGH);
		break;
	case LEFT: // make the two motors on the right of the car rotate clockwise
			   // and the two motors on the left of the car rotate anticlockwise
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M1IN1, GPIO_LOW);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M1IN2, GPIO_HIGH);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M2IN1, GPIO_LOW);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M2IN2, GPIO_HIGH);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M3IN1, GPIO_HIGH);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M3IN2, GPIO_LOW);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M4IN1, GPIO_HIGH);
		GPIO_SetPinValue(MOTORS_PORT, MOTORS_PIN_M4IN2, GPIO_LOW);
		break;
	}
}
void MOTORS_setSpeed(u8 speedPercentage)
{
	TIMER_PWM(speedPercentage, TIMER_NUM_2, TIMER_CHANNEL_1); // change pwm signal with percentage
}